# Site settings
title: 
email: kdw880301@naver.com
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://donghwi-kim.github.io/" # the base hostname & protocol for your site
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
